language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: BK03Xux7VAFqO456nFEpcz0vtR0UerrhtJZkFCI0taW1IDZ5Sy7TsabS96iuXryapRYht77zQvrxImRrtv2qr7HLK4g0SV12cDc57uounU88K7VJLeBivr0kIqj+GFmvYcFYNq//UkGf/T8qIbmExhxgXcqYfyusWU8uRE1LU5tZ5wl7Nt7CoJPTvbUsI+34vS8aOm4IVgom1G0feoSLxvJE+Zv8kiN5hbvHo8Ozpq9mw89mMbakc3yfzw8dy2yq6vY4TM7ep6VyEbw2rOg7hlzdvyFVUhTb7pfXhJHJUv0lz2uWaMM+9MN3BmVQWjlC+2a4MWtQAklCZqq3mXBtFnOGiY6GyGg2EfQiZWIDT3yAc6AI7GST83ohHKqsrP8P2fhWg47TpBc113+TMAWtAxSjsyKbVu639+fVKgrDa1CRyl+Zs9BDP1REKnmYIlBr9pUrbivVN+w9kyYcAwfJeZCDgT44F2l+HArDi8g7fe6p//hMA8NHwelXj4mR2RziEaE1AYVmSTCJlrf0GBuRfQ7kK9vANeX22q16OO+N97d90aCQfbYGHjd83Cf7se7THBjSS55nQpMvsTI6k0gQYPti3l4FhCpzvLXoyxyvwaxC2RuFus62LCo02h68qsEmdM9BAyeAgO815wqza7hxoV/Ne2JE85KgrlVCAgwsCuM=
  app: calm-falls-41670
  on:
    repo: manish237/node-shopping-list-integration-tests
